runtime: nodejs12
service: default
handlers:
  # Serve all static files with urls ending with a file extension
  - url: /(.*\..+)$
    static_files: src/\1
    upload: src/(.*\..+)$
    secure: always
    # catch all handlers to index.html
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always
