steps:
- name: 'gcr.io/cloud-builders/yarn'
  args: [ 'install' ]
- name: 'gcr.io/cloud-builders/yarn'
  args: ["run", "create-env"]
  env:
    - 'REACT_APP_SERVICE_URL=${_REACT_APP_SERVICE_URL}'
    - 'REACT_APP_CAS_AUTH_URL=${_REACT_APP_CAS_AUTH_URL}'
    - 'REACT_APP_BACKEND_AUTH_URL=${_REACT_APP_BACKEND_AUTH_URL}'
    - 'REACT_APP_GQL_URL=${_REACT_APP_GQL_URL}'
    - 'REACT_APP_WS_URL=${_REACT_APP_GRAPHQL_WS_URL}'
    - 'REACT_APP_TOKEN_NAME=${_REACT_APP_TOKEN_NAME}'
- name: 'gcr.io/cloud-builders/yarn'
  args: [ 'run', 'build' ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--version=1']